### PR TITLE
[BUG] Resolve Prophet crash by robustly handling 'stan_backend' and fixing test dimensions

### LINKED ISSUE #9225: [BUG] `Prophet` tests are failing with the failure "`Prophet` object has no attribute `"stan_backend"`
`Prophet` tests are failing with the failure "`Prophet` object has no attribute `"stan_backend"`

Traceback messages - this should be investigated.

```
FAILED sktime/forecasting/trend/tests/test_pwl_trend.py::test_pred_errors_against_linear - AttributeError: 'Prophet' object has no attribute 'stan_backend'
FAILED sktime/forecasting/trend/tests/test_pwl_trend.py::test_for_changes_in_original - AttributeError: 'Prophet' object has no attribute 'stan_backend'
```

### PR DESCRIPTION
**Pull request by DCchoudhury15**
### Description
This PR addresses the CI failures reported in #9225 where `Prophet` tests were crashing with `AttributeError: 'Prophet' object has no attribute 'stan_backend'`. It also fixes `ImportError` issues in trend forecasting and dimension mismatches in the Prophet tests.

### Fixes
1. **Robust `stan_backend` Access:**
   - Modified `_instantiate_model` in `sktime/forecasting/fbprophet.py` and `sktime/forecasting/trend/_pwl_trend_forecaster.py`.
   - The code now uses `getattr(self, "stan_backend", None)` to safely access the attribute. This prevents crashes during testing when the estimator might be inspected or cloned without full initialization.
   - `stan_backend` is now only passed to the upstream Prophet constructor if it is explicitly not `None`.

2. **Trend Class Renaming:**
   - Renamed `PiecewiseLinearTrendForecaster` to `ProphetPiecewiseLinearTrendForecaster` in `_pwl_trend_forecaster.py` to match the expected class name in `test_pwl_trend.py`, resolving the `ImportError`.

3. **Test Correction (`test_prophet.py`):**
   - Updated `test_prophet_fitted_params` to handle scalar values correctly (checking for `.ndim` only if the attribute exists).
   - Updated expected dimensions for `delta` and `beta` parameters from `1` to `2` to match the actual output from the Stan backend.

### Verification
- `pytest sktime/forecasting/trend/tests/test_pwl_trend.py`  (Passed)
- `pytest sktime/forecasting/tests/test_prophet.py`  (Passed)
- `pre-commit` checks  (Passed)

Fixes #9225

### CODE REVIEW

File: sktime/forecasting/trend/_pwl_trend_forecaster.py
Comment (wasup-yash) [inline sktime/forecasting/trend/_pwl_trend_forecaster.py:1]: LGTM(not official reviewer, also remove some obvious comments ig)

Comment (DCchoudhury15) [reply sktime/forecasting/trend/_pwl_trend_forecaster.py:1]: This pr is a work in progress will finalize my solution in a couple of days

**Review by fkiraly — CHANGES_REQUESTED** [review]
It looks like the tests are failing for the `Prophet` forecaster.

May I ask, why are you creating a `_get_fitted_params` method? That seems entirely unrelated to the failure.

File: sktime/forecasting/trend/_pwl_trend_forecaster.py [hunk 1]
```diff
@@ -153,8 +162,11 @@ def _instantiate_model(self):
             mcmc_samples=self.mcmc_samples,
             interval_width=1 - self.alpha,
             uncertainty_samples=self.uncertainty_samples,
-            stan_backend=self.stan_backend,
+            **kwargs,
         )
+        if not hasattr(self._forecaster, "stan_backend"):
```
Comment (fkiraly) [inline sktime/forecasting/trend/_pwl_trend_forecaster.py]: doing this seems unsafe. Why are we doing this?

Comment (DCchoudhury15) [reply sktime/forecasting/trend/_pwl_trend_forecaster.py]: Thanks for correcting my approach @fkiraly! You were right about _get_fitted_params being out of scope, so I’ve gone ahead and scrapped that idea entirely. I've been experimenting with a couple of ways to fix the main crash locally mostly deciding between just checking if stan_backend is None before passing it (which seems cleaner) versus explicitly gating it behind a prophet < 1.1 version check. Both seem to work, but I was leaning towards the simpler check. I also noticed that I needed to slightly update the test expectations since the newer Prophet returns 2D arrays now. I was planning to push the simpler logic fix along with that test update, but I wanted to double-check with you first: do you prefer the explicit version check, or is the logic-based one satisfactory?

**Comment by DCchoudhury15** [comment]
Hi @fkiraly,

Just following up on this. The code fix is working tests pass locally with Prophet 1.3.0.

The CI failures are a different problem though. I traced it to a version constraint mismatch in `pyproject.toml`:

- Line 94 (`all_extras`): `prophet>=1.1` → installs 1.3.0 → tests pass
- Line 184 (`forecasting`): `prophet<1.2,>=1.1` → installs 1.1.5 → tests fail

Prophet 1.1.5 has a bug where `_load_stan_backend()` fails silently and never sets `self.stan_backend`, so the `AttributeError` happens inside Prophet itself  not something sktime's code can fix.

I've bumped the `forecasting` constraint to `prophet>=1.2` in this PR to match.
