### ISSUE TITLE
Issues faced while installing development version on windows machine.

### ISSUE THREAD

**Issue by Piyush1729** [alan-turing-institute/sktime#1550]
I am working on windows 10 OS, Anaconda 4.5.4. After following the instructions for the development version given in https://www.sktime.org/en/latest/installation.html, Here is my feedback:
Requirements.txt says fbprophet is needed but https://www.sktime.org/en/latest/installation.html#facebook-prophet says install prophet. There's a clash here as both require different versions of cmdstanpy.
Also, 2.19 version of pystan is not compilable in my environment for some reason, hence installed 2.18 version, which worked fine.
I installed build tools 2019, but during installation of pystan "conda install libpython m2w64-toolchain -c msys2" was run, and maybe due to this during compiling sktime, MinGW is being used as opposed to msvc, this caused compilation error due to openmp. Hence pip editable install did not work for me.
As a solution, I had to "python setup.py build --compiler=msvc install", which finally worked.

**Comment by TonyBagnall** [comment]
hi, I feel your pain having tried this over the weekend, I will have a go at sorting it out

**Comment by mloning** [comment]
Closed in favour of #1372
