### ISSUE TITLE
[BUG] no module named sktime.forecasting 

### ISSUE THREAD

**Issue by ZhuFanCheng** [alan-turing-institute/sktime#2068]
**Describe the bug**

Can't import anything from sktime.forecasting, get "no module named ..." error

**To Reproduce**

from sktime.forecasting.exp_smoothing import ExponentialSmoothing

```python
from sktime.forecasting.exp_smoothing import ExponentialSmoothing
```

**Expected behavior**

Expect to be able to import the library

**Additional context**

working in python 3.8.12

**Versions**
<details>

Please run the following code snippet and paste the output here:
 
"ImportError: cannot import name 'show_versions' from 'sktime' (/opt/homebrew/lib/python3.9/site-packages/sktime/__init__.py)"

</details>

**Comment by aiwalter** [comment]
which version is this? how did you install `sktime`?

**Comment by ZhuFanCheng** [comment]
I pip-installed sktime. You mean version of what?

**Comment by aiwalter** [comment]
version of sktime that you installed, I guess then its most recent one from PyPI

**Comment by fkiraly** [comment]
I cannot reproduce this on 0.10.0, windows, python 3.8.
Import works for me.

**Comment by fkiraly** [comment]
hm, this sounds like a faulty environment or incomplete installation.
You could join one of the community sessions on Friday (8am or 1pm UTC) and we could do some troubleshoot by screenshare.

**Comment by fkiraly** [comment]
no activity for one month, requested details not provided. Closing.
