### PR TITLE
[BUG] Fix KNeighborsTimeSeriesClassifier.neighbor() failed

### LINKED ISSUE #6515: [BUG] KNeighborsTimeSeriesClassifier.neighbor() failed
**Describe the bug**
The bug was found when I ran https://github.com/sktime/sktime/blob/main/sktime/classification/distance_based/tests/test_time_series_neighbors.py#L127-L147

If setting `algorithm='brute'`, it runs well.
```python
kntsc = KNeighborsTimeSeriesClassifier(n_neighbors=1, algorithm='brute')
kntsc.fit(Xtrain, ytrain)
ret = kntsc.kneighbors(Xtest)
```
But if setting `algorithm='ball_tree'`, it will fail.
```python
kntsc = KNeighborsTimeSeriesClassifier(n_neighbors=1, algorithm='ball_tree')
kntsc.fit(Xtrain, ytrain)
ret = kntsc.kneighbors(Xtest)
```
```
Traceback (most recent call last):
  File "sktime\sktime\classification\distance_based\tests\test_time_series_neighbors.py", line 149, in <module>
    test_knn_kneighbors()
  File "sktime\sktime\classification\distance_based\tests\test_time_series_neighbors.py", line 139, in test_knn_kneighbors
    ret = kntsc.kneighbors(Xtest)
  File "sktime\sktime\distances\adapters\sklearn.py", line 131, in kneighbors
    dist_mat = self._distance(X, self._X)
AttributeError: 'KNeighborsTimeSeriesClassifier' object has no attribute '_X'
```

This is because it runs different `_fit` functions when setting different algorithms. [_fit_precomp](https://github.com/sktime/sktime/blob/main/sktime/classification/distance_based/_time_series_neighbors.py#L341-L344) runs `self._X = X` but [_fit_dist](https://github.com/sktime/sktime/blob/main/sktime/classification/distance_based/_time_series_neighbors.py#L310) not.

In fact, it's caused by #5937

I'm not clear about if this is a mistake or we shouldn't run `KNeighborsTimeSeriesClassifier.neighbor` when setting `algorithm='ball_tree'`.

### PR DESCRIPTION
**Pull request by Ankit-1204**
#### Reference Issues/PRs
Fixes #6515 

#### What does this implement/fix? Explain your changes.

Fixes error received when running `KNeighborsTimeSeriesClassifier.neighbor` using `algorithm='ball_tree'`

### CODE REVIEW

**Comment by Ankit-1204** [comment]
Meant to open as a draft PR.

**Review by fkiraly — CHANGES_REQUESTED** [review]
Great! Could you add a test?

**Review by fkiraly — APPROVED** [review]
Great, thanks!
